// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class AreaModel;
@class AreaModelBuilder;



@interface AreaModelRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define AreaModel_AreaId @"areaId"
#define AreaModel_AreaName @"areaName"
@interface AreaModel : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAreaId_:1;
  BOOL hasAreaName_:1;
  SInt32 areaId;
  NSString* areaName;
}
- (BOOL) hasAreaId;
- (BOOL) hasAreaName;
@property (readonly) SInt32 areaId;
@property (readonly, strong) NSString* areaName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AreaModelBuilder*) builder;
+ (AreaModelBuilder*) builder;
+ (AreaModelBuilder*) builderWithPrototype:(AreaModel*) prototype;
- (AreaModelBuilder*) toBuilder;

+ (AreaModel*) parseFromData:(NSData*) data;
+ (AreaModel*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AreaModel*) parseFromInputStream:(NSInputStream*) input;
+ (AreaModel*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AreaModel*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AreaModel*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AreaModelBuilder : PBGeneratedMessageBuilder {
@private
  AreaModel* resultAreaModel;
}

- (AreaModel*) defaultInstance;

- (AreaModelBuilder*) clear;
- (AreaModelBuilder*) clone;

- (AreaModel*) build;
- (AreaModel*) buildPartial;

- (AreaModelBuilder*) mergeFrom:(AreaModel*) other;
- (AreaModelBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AreaModelBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAreaId;
- (SInt32) areaId;
- (AreaModelBuilder*) setAreaId:(SInt32) value;
- (AreaModelBuilder*) clearAreaId;

- (BOOL) hasAreaName;
- (NSString*) areaName;
- (AreaModelBuilder*) setAreaName:(NSString*) value;
- (AreaModelBuilder*) clearAreaName;
@end


// @@protoc_insertion_point(global_scope)
