// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "BasicDataModel.pb.h"
// @@protoc_insertion_point(imports)

@implementation BasicDataModelRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [BasicDataModelRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [ProvinceModelRoot registerAllExtensions:registry];
    [PositionModelRoot registerAllExtensions:registry];
    [IndustryModelRoot registerAllExtensions:registry];
    [ProductStageModelRoot registerAllExtensions:registry];
    [FinancingStageModelRoot registerAllExtensions:registry];
    [KeyValuePairStringBoolRoot registerAllExtensions:registry];
    [ServiceScopeModelRoot registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface BasicDataModel ()
@property (strong) NSMutableArray * provinceListArray;
@property (strong) NSMutableArray * positionListArray;
@property (strong) NSMutableArray * industryListArray;
@property (strong) NSMutableArray * productStageListArray;
@property (strong) NSMutableArray * financingStageListArray;
@property (strong) NSMutableArray * shareListArray;
@property (strong) NSMutableArray * serviceScopeListArray;
@end

@implementation BasicDataModel

@synthesize provinceListArray;
@dynamic provinceList;
@synthesize positionListArray;
@dynamic positionList;
@synthesize industryListArray;
@dynamic industryList;
@synthesize productStageListArray;
@dynamic productStageList;
@synthesize financingStageListArray;
@dynamic financingStageList;
@synthesize shareListArray;
@dynamic shareList;
@synthesize serviceScopeListArray;
@dynamic serviceScopeList;
- (instancetype) init {
  if ((self = [super init])) {
  }
  return self;
}
static BasicDataModel* defaultBasicDataModelInstance = nil;
+ (void) initialize {
  if (self == [BasicDataModel class]) {
    defaultBasicDataModelInstance = [[BasicDataModel alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultBasicDataModelInstance;
}
- (instancetype) defaultInstance {
  return defaultBasicDataModelInstance;
}
- (NSArray *)provinceList {
  return provinceListArray;
}
- (ProvinceModel*)provinceListAtIndex:(NSUInteger)index {
  return [provinceListArray objectAtIndex:index];
}
- (NSArray *)positionList {
  return positionListArray;
}
- (PositionModel*)positionListAtIndex:(NSUInteger)index {
  return [positionListArray objectAtIndex:index];
}
- (NSArray *)industryList {
  return industryListArray;
}
- (IndustryModel*)industryListAtIndex:(NSUInteger)index {
  return [industryListArray objectAtIndex:index];
}
- (NSArray *)productStageList {
  return productStageListArray;
}
- (ProductStageModel*)productStageListAtIndex:(NSUInteger)index {
  return [productStageListArray objectAtIndex:index];
}
- (NSArray *)financingStageList {
  return financingStageListArray;
}
- (FinancingStageModel*)financingStageListAtIndex:(NSUInteger)index {
  return [financingStageListArray objectAtIndex:index];
}
- (NSArray *)shareList {
  return shareListArray;
}
- (KeyValuePairStringBool*)shareListAtIndex:(NSUInteger)index {
  return [shareListArray objectAtIndex:index];
}
- (NSArray *)serviceScopeList {
  return serviceScopeListArray;
}
- (ServiceScopeModel*)serviceScopeListAtIndex:(NSUInteger)index {
  return [serviceScopeListArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self.provinceListArray enumerateObjectsUsingBlock:^(ProvinceModel *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:1 value:element];
  }];
  [self.positionListArray enumerateObjectsUsingBlock:^(PositionModel *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:2 value:element];
  }];
  [self.industryListArray enumerateObjectsUsingBlock:^(IndustryModel *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:3 value:element];
  }];
  [self.productStageListArray enumerateObjectsUsingBlock:^(ProductStageModel *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:4 value:element];
  }];
  [self.financingStageListArray enumerateObjectsUsingBlock:^(FinancingStageModel *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:5 value:element];
  }];
  [self.shareListArray enumerateObjectsUsingBlock:^(KeyValuePairStringBool *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:6 value:element];
  }];
  [self.serviceScopeListArray enumerateObjectsUsingBlock:^(ServiceScopeModel *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:7 value:element];
  }];
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  [self.provinceListArray enumerateObjectsUsingBlock:^(ProvinceModel *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(1, element);
  }];
  [self.positionListArray enumerateObjectsUsingBlock:^(PositionModel *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(2, element);
  }];
  [self.industryListArray enumerateObjectsUsingBlock:^(IndustryModel *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(3, element);
  }];
  [self.productStageListArray enumerateObjectsUsingBlock:^(ProductStageModel *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(4, element);
  }];
  [self.financingStageListArray enumerateObjectsUsingBlock:^(FinancingStageModel *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(5, element);
  }];
  [self.shareListArray enumerateObjectsUsingBlock:^(KeyValuePairStringBool *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(6, element);
  }];
  [self.serviceScopeListArray enumerateObjectsUsingBlock:^(ServiceScopeModel *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(7, element);
  }];
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (BasicDataModel*) parseFromData:(NSData*) data {
  return (BasicDataModel*)[[[BasicDataModel builder] mergeFromData:data] build];
}
+ (BasicDataModel*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BasicDataModel*)[[[BasicDataModel builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (BasicDataModel*) parseFromInputStream:(NSInputStream*) input {
  return (BasicDataModel*)[[[BasicDataModel builder] mergeFromInputStream:input] build];
}
+ (BasicDataModel*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BasicDataModel*)[[[BasicDataModel builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BasicDataModel*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (BasicDataModel*)[[[BasicDataModel builder] mergeFromCodedInputStream:input] build];
}
+ (BasicDataModel*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BasicDataModel*)[[[BasicDataModel builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BasicDataModelBuilder*) builder {
  return [[BasicDataModelBuilder alloc] init];
}
+ (BasicDataModelBuilder*) builderWithPrototype:(BasicDataModel*) prototype {
  return [[BasicDataModel builder] mergeFrom:prototype];
}
- (BasicDataModelBuilder*) builder {
  return [BasicDataModel builder];
}
- (BasicDataModelBuilder*) toBuilder {
  return [BasicDataModel builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  [self.provinceListArray enumerateObjectsUsingBlock:^(ProvinceModel *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"provinceList"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.positionListArray enumerateObjectsUsingBlock:^(PositionModel *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"positionList"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.industryListArray enumerateObjectsUsingBlock:^(IndustryModel *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"industryList"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.productStageListArray enumerateObjectsUsingBlock:^(ProductStageModel *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"productStageList"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.financingStageListArray enumerateObjectsUsingBlock:^(FinancingStageModel *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"financingStageList"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.shareListArray enumerateObjectsUsingBlock:^(KeyValuePairStringBool *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"shareList"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.serviceScopeListArray enumerateObjectsUsingBlock:^(ServiceScopeModel *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"serviceScopeList"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  for (ProvinceModel* element in self.provinceListArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"provinceList"];
  }
  for (PositionModel* element in self.positionListArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"positionList"];
  }
  for (IndustryModel* element in self.industryListArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"industryList"];
  }
  for (ProductStageModel* element in self.productStageListArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"productStageList"];
  }
  for (FinancingStageModel* element in self.financingStageListArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"financingStageList"];
  }
  for (KeyValuePairStringBool* element in self.shareListArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"shareList"];
  }
  for (ServiceScopeModel* element in self.serviceScopeListArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"serviceScopeList"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[BasicDataModel class]]) {
    return NO;
  }
  BasicDataModel *otherMessage = other;
  return
      [self.provinceListArray isEqualToArray:otherMessage.provinceListArray] &&
      [self.positionListArray isEqualToArray:otherMessage.positionListArray] &&
      [self.industryListArray isEqualToArray:otherMessage.industryListArray] &&
      [self.productStageListArray isEqualToArray:otherMessage.productStageListArray] &&
      [self.financingStageListArray isEqualToArray:otherMessage.financingStageListArray] &&
      [self.shareListArray isEqualToArray:otherMessage.shareListArray] &&
      [self.serviceScopeListArray isEqualToArray:otherMessage.serviceScopeListArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  [self.provinceListArray enumerateObjectsUsingBlock:^(ProvinceModel *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  [self.positionListArray enumerateObjectsUsingBlock:^(PositionModel *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  [self.industryListArray enumerateObjectsUsingBlock:^(IndustryModel *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  [self.productStageListArray enumerateObjectsUsingBlock:^(ProductStageModel *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  [self.financingStageListArray enumerateObjectsUsingBlock:^(FinancingStageModel *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  [self.shareListArray enumerateObjectsUsingBlock:^(KeyValuePairStringBool *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  [self.serviceScopeListArray enumerateObjectsUsingBlock:^(ServiceScopeModel *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface BasicDataModelBuilder()
@property (strong) BasicDataModel* resultBasicDataModel;
@end

@implementation BasicDataModelBuilder
@synthesize resultBasicDataModel;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultBasicDataModel = [[BasicDataModel alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultBasicDataModel;
}
- (BasicDataModelBuilder*) clear {
  self.resultBasicDataModel = [[BasicDataModel alloc] init];
  return self;
}
- (BasicDataModelBuilder*) clone {
  return [BasicDataModel builderWithPrototype:resultBasicDataModel];
}
- (BasicDataModel*) defaultInstance {
  return [BasicDataModel defaultInstance];
}
- (BasicDataModel*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (BasicDataModel*) buildPartial {
  BasicDataModel* returnMe = resultBasicDataModel;
  self.resultBasicDataModel = nil;
  return returnMe;
}
- (BasicDataModelBuilder*) mergeFrom:(BasicDataModel*) other {
  if (other == [BasicDataModel defaultInstance]) {
    return self;
  }
  if (other.provinceListArray.count > 0) {
    if (resultBasicDataModel.provinceListArray == nil) {
      resultBasicDataModel.provinceListArray = [[NSMutableArray alloc] initWithArray:other.provinceListArray];
    } else {
      [resultBasicDataModel.provinceListArray addObjectsFromArray:other.provinceListArray];
    }
  }
  if (other.positionListArray.count > 0) {
    if (resultBasicDataModel.positionListArray == nil) {
      resultBasicDataModel.positionListArray = [[NSMutableArray alloc] initWithArray:other.positionListArray];
    } else {
      [resultBasicDataModel.positionListArray addObjectsFromArray:other.positionListArray];
    }
  }
  if (other.industryListArray.count > 0) {
    if (resultBasicDataModel.industryListArray == nil) {
      resultBasicDataModel.industryListArray = [[NSMutableArray alloc] initWithArray:other.industryListArray];
    } else {
      [resultBasicDataModel.industryListArray addObjectsFromArray:other.industryListArray];
    }
  }
  if (other.productStageListArray.count > 0) {
    if (resultBasicDataModel.productStageListArray == nil) {
      resultBasicDataModel.productStageListArray = [[NSMutableArray alloc] initWithArray:other.productStageListArray];
    } else {
      [resultBasicDataModel.productStageListArray addObjectsFromArray:other.productStageListArray];
    }
  }
  if (other.financingStageListArray.count > 0) {
    if (resultBasicDataModel.financingStageListArray == nil) {
      resultBasicDataModel.financingStageListArray = [[NSMutableArray alloc] initWithArray:other.financingStageListArray];
    } else {
      [resultBasicDataModel.financingStageListArray addObjectsFromArray:other.financingStageListArray];
    }
  }
  if (other.shareListArray.count > 0) {
    if (resultBasicDataModel.shareListArray == nil) {
      resultBasicDataModel.shareListArray = [[NSMutableArray alloc] initWithArray:other.shareListArray];
    } else {
      [resultBasicDataModel.shareListArray addObjectsFromArray:other.shareListArray];
    }
  }
  if (other.serviceScopeListArray.count > 0) {
    if (resultBasicDataModel.serviceScopeListArray == nil) {
      resultBasicDataModel.serviceScopeListArray = [[NSMutableArray alloc] initWithArray:other.serviceScopeListArray];
    } else {
      [resultBasicDataModel.serviceScopeListArray addObjectsFromArray:other.serviceScopeListArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (BasicDataModelBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (BasicDataModelBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        ProvinceModelBuilder* subBuilder = [ProvinceModel builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addProvinceList:[subBuilder buildPartial]];
        break;
      }
      case 18: {
        PositionModelBuilder* subBuilder = [PositionModel builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addPositionList:[subBuilder buildPartial]];
        break;
      }
      case 26: {
        IndustryModelBuilder* subBuilder = [IndustryModel builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addIndustryList:[subBuilder buildPartial]];
        break;
      }
      case 34: {
        ProductStageModelBuilder* subBuilder = [ProductStageModel builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addProductStageList:[subBuilder buildPartial]];
        break;
      }
      case 42: {
        FinancingStageModelBuilder* subBuilder = [FinancingStageModel builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addFinancingStageList:[subBuilder buildPartial]];
        break;
      }
      case 50: {
        KeyValuePairStringBoolBuilder* subBuilder = [KeyValuePairStringBool builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addShareList:[subBuilder buildPartial]];
        break;
      }
      case 58: {
        ServiceScopeModelBuilder* subBuilder = [ServiceScopeModel builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addServiceScopeList:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSMutableArray *)provinceList {
  return resultBasicDataModel.provinceListArray;
}
- (ProvinceModel*)provinceListAtIndex:(NSUInteger)index {
  return [resultBasicDataModel provinceListAtIndex:index];
}
- (BasicDataModelBuilder *)addProvinceList:(ProvinceModel*)value {
  if (resultBasicDataModel.provinceListArray == nil) {
    resultBasicDataModel.provinceListArray = [[NSMutableArray alloc]init];
  }
  [resultBasicDataModel.provinceListArray addObject:value];
  return self;
}
- (BasicDataModelBuilder *)setProvinceListArray:(NSArray *)array {
  resultBasicDataModel.provinceListArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (BasicDataModelBuilder *)clearProvinceList {
  resultBasicDataModel.provinceListArray = nil;
  return self;
}
- (NSMutableArray *)positionList {
  return resultBasicDataModel.positionListArray;
}
- (PositionModel*)positionListAtIndex:(NSUInteger)index {
  return [resultBasicDataModel positionListAtIndex:index];
}
- (BasicDataModelBuilder *)addPositionList:(PositionModel*)value {
  if (resultBasicDataModel.positionListArray == nil) {
    resultBasicDataModel.positionListArray = [[NSMutableArray alloc]init];
  }
  [resultBasicDataModel.positionListArray addObject:value];
  return self;
}
- (BasicDataModelBuilder *)setPositionListArray:(NSArray *)array {
  resultBasicDataModel.positionListArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (BasicDataModelBuilder *)clearPositionList {
  resultBasicDataModel.positionListArray = nil;
  return self;
}
- (NSMutableArray *)industryList {
  return resultBasicDataModel.industryListArray;
}
- (IndustryModel*)industryListAtIndex:(NSUInteger)index {
  return [resultBasicDataModel industryListAtIndex:index];
}
- (BasicDataModelBuilder *)addIndustryList:(IndustryModel*)value {
  if (resultBasicDataModel.industryListArray == nil) {
    resultBasicDataModel.industryListArray = [[NSMutableArray alloc]init];
  }
  [resultBasicDataModel.industryListArray addObject:value];
  return self;
}
- (BasicDataModelBuilder *)setIndustryListArray:(NSArray *)array {
  resultBasicDataModel.industryListArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (BasicDataModelBuilder *)clearIndustryList {
  resultBasicDataModel.industryListArray = nil;
  return self;
}
- (NSMutableArray *)productStageList {
  return resultBasicDataModel.productStageListArray;
}
- (ProductStageModel*)productStageListAtIndex:(NSUInteger)index {
  return [resultBasicDataModel productStageListAtIndex:index];
}
- (BasicDataModelBuilder *)addProductStageList:(ProductStageModel*)value {
  if (resultBasicDataModel.productStageListArray == nil) {
    resultBasicDataModel.productStageListArray = [[NSMutableArray alloc]init];
  }
  [resultBasicDataModel.productStageListArray addObject:value];
  return self;
}
- (BasicDataModelBuilder *)setProductStageListArray:(NSArray *)array {
  resultBasicDataModel.productStageListArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (BasicDataModelBuilder *)clearProductStageList {
  resultBasicDataModel.productStageListArray = nil;
  return self;
}
- (NSMutableArray *)financingStageList {
  return resultBasicDataModel.financingStageListArray;
}
- (FinancingStageModel*)financingStageListAtIndex:(NSUInteger)index {
  return [resultBasicDataModel financingStageListAtIndex:index];
}
- (BasicDataModelBuilder *)addFinancingStageList:(FinancingStageModel*)value {
  if (resultBasicDataModel.financingStageListArray == nil) {
    resultBasicDataModel.financingStageListArray = [[NSMutableArray alloc]init];
  }
  [resultBasicDataModel.financingStageListArray addObject:value];
  return self;
}
- (BasicDataModelBuilder *)setFinancingStageListArray:(NSArray *)array {
  resultBasicDataModel.financingStageListArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (BasicDataModelBuilder *)clearFinancingStageList {
  resultBasicDataModel.financingStageListArray = nil;
  return self;
}
- (NSMutableArray *)shareList {
  return resultBasicDataModel.shareListArray;
}
- (KeyValuePairStringBool*)shareListAtIndex:(NSUInteger)index {
  return [resultBasicDataModel shareListAtIndex:index];
}
- (BasicDataModelBuilder *)addShareList:(KeyValuePairStringBool*)value {
  if (resultBasicDataModel.shareListArray == nil) {
    resultBasicDataModel.shareListArray = [[NSMutableArray alloc]init];
  }
  [resultBasicDataModel.shareListArray addObject:value];
  return self;
}
- (BasicDataModelBuilder *)setShareListArray:(NSArray *)array {
  resultBasicDataModel.shareListArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (BasicDataModelBuilder *)clearShareList {
  resultBasicDataModel.shareListArray = nil;
  return self;
}
- (NSMutableArray *)serviceScopeList {
  return resultBasicDataModel.serviceScopeListArray;
}
- (ServiceScopeModel*)serviceScopeListAtIndex:(NSUInteger)index {
  return [resultBasicDataModel serviceScopeListAtIndex:index];
}
- (BasicDataModelBuilder *)addServiceScopeList:(ServiceScopeModel*)value {
  if (resultBasicDataModel.serviceScopeListArray == nil) {
    resultBasicDataModel.serviceScopeListArray = [[NSMutableArray alloc]init];
  }
  [resultBasicDataModel.serviceScopeListArray addObject:value];
  return self;
}
- (BasicDataModelBuilder *)setServiceScopeListArray:(NSArray *)array {
  resultBasicDataModel.serviceScopeListArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (BasicDataModelBuilder *)clearServiceScopeList {
  resultBasicDataModel.serviceScopeListArray = nil;
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
