// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class FinancingStageModel;
@class FinancingStageModelBuilder;



@interface FinancingStageModelRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define FinancingStageModel_FinancingStageId @"financingStageId"
#define FinancingStageModel_FinancingStageName @"financingStageName"
#define FinancingStageModel_FontColor @"fontColor"
@interface FinancingStageModel : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFinancingStageId_:1;
  BOOL hasFinancingStageName_:1;
  BOOL hasFontColor_:1;
  SInt32 financingStageId;
  NSString* financingStageName;
  NSString* fontColor;
}
- (BOOL) hasFinancingStageId;
- (BOOL) hasFinancingStageName;
- (BOOL) hasFontColor;
@property (readonly) SInt32 financingStageId;
@property (readonly, strong) NSString* financingStageName;
@property (readonly, strong) NSString* fontColor;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FinancingStageModelBuilder*) builder;
+ (FinancingStageModelBuilder*) builder;
+ (FinancingStageModelBuilder*) builderWithPrototype:(FinancingStageModel*) prototype;
- (FinancingStageModelBuilder*) toBuilder;

+ (FinancingStageModel*) parseFromData:(NSData*) data;
+ (FinancingStageModel*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FinancingStageModel*) parseFromInputStream:(NSInputStream*) input;
+ (FinancingStageModel*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FinancingStageModel*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FinancingStageModel*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FinancingStageModelBuilder : PBGeneratedMessageBuilder {
@private
  FinancingStageModel* resultFinancingStageModel;
}

- (FinancingStageModel*) defaultInstance;

- (FinancingStageModelBuilder*) clear;
- (FinancingStageModelBuilder*) clone;

- (FinancingStageModel*) build;
- (FinancingStageModel*) buildPartial;

- (FinancingStageModelBuilder*) mergeFrom:(FinancingStageModel*) other;
- (FinancingStageModelBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FinancingStageModelBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFinancingStageId;
- (SInt32) financingStageId;
- (FinancingStageModelBuilder*) setFinancingStageId:(SInt32) value;
- (FinancingStageModelBuilder*) clearFinancingStageId;

- (BOOL) hasFinancingStageName;
- (NSString*) financingStageName;
- (FinancingStageModelBuilder*) setFinancingStageName:(NSString*) value;
- (FinancingStageModelBuilder*) clearFinancingStageName;

- (BOOL) hasFontColor;
- (NSString*) fontColor;
- (FinancingStageModelBuilder*) setFontColor:(NSString*) value;
- (FinancingStageModelBuilder*) clearFontColor;
@end


// @@protoc_insertion_point(global_scope)
