// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "KeyValuePairStringBool.pb.h"
// @@protoc_insertion_point(imports)

@implementation KeyValuePairStringBoolRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [KeyValuePairStringBoolRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface KeyValuePairStringBool ()
@property (strong) NSString* stringKey;
@property BOOL stringValue;
@end

@implementation KeyValuePairStringBool

- (BOOL) hasStringKey {
  return !!hasStringKey_;
}
- (void) setHasStringKey:(BOOL) _value_ {
  hasStringKey_ = !!_value_;
}
@synthesize stringKey;
- (BOOL) hasStringValue {
  return !!hasStringValue_;
}
- (void) setHasStringValue:(BOOL) _value_ {
  hasStringValue_ = !!_value_;
}
- (BOOL) stringValue {
  return !!stringValue_;
}
- (void) setStringValue:(BOOL) _value_ {
  stringValue_ = !!_value_;
}
- (instancetype) init {
  if ((self = [super init])) {
    self.stringKey = @"";
    self.stringValue = NO;
  }
  return self;
}
static KeyValuePairStringBool* defaultKeyValuePairStringBoolInstance = nil;
+ (void) initialize {
  if (self == [KeyValuePairStringBool class]) {
    defaultKeyValuePairStringBoolInstance = [[KeyValuePairStringBool alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultKeyValuePairStringBoolInstance;
}
- (instancetype) defaultInstance {
  return defaultKeyValuePairStringBoolInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasStringKey) {
    [output writeString:1 value:self.stringKey];
  }
  if (self.hasStringValue) {
    [output writeBool:2 value:self.stringValue];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasStringKey) {
    size_ += computeStringSize(1, self.stringKey);
  }
  if (self.hasStringValue) {
    size_ += computeBoolSize(2, self.stringValue);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (KeyValuePairStringBool*) parseFromData:(NSData*) data {
  return (KeyValuePairStringBool*)[[[KeyValuePairStringBool builder] mergeFromData:data] build];
}
+ (KeyValuePairStringBool*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (KeyValuePairStringBool*)[[[KeyValuePairStringBool builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (KeyValuePairStringBool*) parseFromInputStream:(NSInputStream*) input {
  return (KeyValuePairStringBool*)[[[KeyValuePairStringBool builder] mergeFromInputStream:input] build];
}
+ (KeyValuePairStringBool*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (KeyValuePairStringBool*)[[[KeyValuePairStringBool builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (KeyValuePairStringBool*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (KeyValuePairStringBool*)[[[KeyValuePairStringBool builder] mergeFromCodedInputStream:input] build];
}
+ (KeyValuePairStringBool*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (KeyValuePairStringBool*)[[[KeyValuePairStringBool builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (KeyValuePairStringBoolBuilder*) builder {
  return [[KeyValuePairStringBoolBuilder alloc] init];
}
+ (KeyValuePairStringBoolBuilder*) builderWithPrototype:(KeyValuePairStringBool*) prototype {
  return [[KeyValuePairStringBool builder] mergeFrom:prototype];
}
- (KeyValuePairStringBoolBuilder*) builder {
  return [KeyValuePairStringBool builder];
}
- (KeyValuePairStringBoolBuilder*) toBuilder {
  return [KeyValuePairStringBool builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasStringKey) {
    [output appendFormat:@"%@%@: %@\n", indent, @"stringKey", self.stringKey];
  }
  if (self.hasStringValue) {
    [output appendFormat:@"%@%@: %@\n", indent, @"stringValue", [NSNumber numberWithBool:self.stringValue]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasStringKey) {
    [dictionary setObject: self.stringKey forKey: @"stringKey"];
  }
  if (self.hasStringValue) {
    [dictionary setObject: [NSNumber numberWithBool:self.stringValue] forKey: @"stringValue"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[KeyValuePairStringBool class]]) {
    return NO;
  }
  KeyValuePairStringBool *otherMessage = other;
  return
      self.hasStringKey == otherMessage.hasStringKey &&
      (!self.hasStringKey || [self.stringKey isEqual:otherMessage.stringKey]) &&
      self.hasStringValue == otherMessage.hasStringValue &&
      (!self.hasStringValue || self.stringValue == otherMessage.stringValue) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasStringKey) {
    hashCode = hashCode * 31 + [self.stringKey hash];
  }
  if (self.hasStringValue) {
    hashCode = hashCode * 31 + [[NSNumber numberWithBool:self.stringValue] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface KeyValuePairStringBoolBuilder()
@property (strong) KeyValuePairStringBool* resultKeyValuePairStringBool;
@end

@implementation KeyValuePairStringBoolBuilder
@synthesize resultKeyValuePairStringBool;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultKeyValuePairStringBool = [[KeyValuePairStringBool alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultKeyValuePairStringBool;
}
- (KeyValuePairStringBoolBuilder*) clear {
  self.resultKeyValuePairStringBool = [[KeyValuePairStringBool alloc] init];
  return self;
}
- (KeyValuePairStringBoolBuilder*) clone {
  return [KeyValuePairStringBool builderWithPrototype:resultKeyValuePairStringBool];
}
- (KeyValuePairStringBool*) defaultInstance {
  return [KeyValuePairStringBool defaultInstance];
}
- (KeyValuePairStringBool*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (KeyValuePairStringBool*) buildPartial {
  KeyValuePairStringBool* returnMe = resultKeyValuePairStringBool;
  self.resultKeyValuePairStringBool = nil;
  return returnMe;
}
- (KeyValuePairStringBoolBuilder*) mergeFrom:(KeyValuePairStringBool*) other {
  if (other == [KeyValuePairStringBool defaultInstance]) {
    return self;
  }
  if (other.hasStringKey) {
    [self setStringKey:other.stringKey];
  }
  if (other.hasStringValue) {
    [self setStringValue:other.stringValue];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (KeyValuePairStringBoolBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (KeyValuePairStringBoolBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setStringKey:[input readString]];
        break;
      }
      case 16: {
        [self setStringValue:[input readBool]];
        break;
      }
    }
  }
}
- (BOOL) hasStringKey {
  return resultKeyValuePairStringBool.hasStringKey;
}
- (NSString*) stringKey {
  return resultKeyValuePairStringBool.stringKey;
}
- (KeyValuePairStringBoolBuilder*) setStringKey:(NSString*) value {
  resultKeyValuePairStringBool.hasStringKey = YES;
  resultKeyValuePairStringBool.stringKey = value;
  return self;
}
- (KeyValuePairStringBoolBuilder*) clearStringKey {
  resultKeyValuePairStringBool.hasStringKey = NO;
  resultKeyValuePairStringBool.stringKey = @"";
  return self;
}
- (BOOL) hasStringValue {
  return resultKeyValuePairStringBool.hasStringValue;
}
- (BOOL) stringValue {
  return resultKeyValuePairStringBool.stringValue;
}
- (KeyValuePairStringBoolBuilder*) setStringValue:(BOOL) value {
  resultKeyValuePairStringBool.hasStringValue = YES;
  resultKeyValuePairStringBool.stringValue = value;
  return self;
}
- (KeyValuePairStringBoolBuilder*) clearStringValue {
  resultKeyValuePairStringBool.hasStringValue = NO;
  resultKeyValuePairStringBool.stringValue = NO;
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
