// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class KeyValuePairStringBool;
@class KeyValuePairStringBoolBuilder;



@interface KeyValuePairStringBoolRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define KeyValuePairStringBool_StringKey @"stringKey"
#define KeyValuePairStringBool_StringValue @"stringValue"
@interface KeyValuePairStringBool : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStringValue_:1;
  BOOL hasStringKey_:1;
  BOOL stringValue_:1;
  NSString* stringKey;
}
- (BOOL) hasStringKey;
- (BOOL) hasStringValue;
@property (readonly, strong) NSString* stringKey;
- (BOOL) stringValue;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (KeyValuePairStringBoolBuilder*) builder;
+ (KeyValuePairStringBoolBuilder*) builder;
+ (KeyValuePairStringBoolBuilder*) builderWithPrototype:(KeyValuePairStringBool*) prototype;
- (KeyValuePairStringBoolBuilder*) toBuilder;

+ (KeyValuePairStringBool*) parseFromData:(NSData*) data;
+ (KeyValuePairStringBool*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (KeyValuePairStringBool*) parseFromInputStream:(NSInputStream*) input;
+ (KeyValuePairStringBool*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (KeyValuePairStringBool*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (KeyValuePairStringBool*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface KeyValuePairStringBoolBuilder : PBGeneratedMessageBuilder {
@private
  KeyValuePairStringBool* resultKeyValuePairStringBool;
}

- (KeyValuePairStringBool*) defaultInstance;

- (KeyValuePairStringBoolBuilder*) clear;
- (KeyValuePairStringBoolBuilder*) clone;

- (KeyValuePairStringBool*) build;
- (KeyValuePairStringBool*) buildPartial;

- (KeyValuePairStringBoolBuilder*) mergeFrom:(KeyValuePairStringBool*) other;
- (KeyValuePairStringBoolBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (KeyValuePairStringBoolBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStringKey;
- (NSString*) stringKey;
- (KeyValuePairStringBoolBuilder*) setStringKey:(NSString*) value;
- (KeyValuePairStringBoolBuilder*) clearStringKey;

- (BOOL) hasStringValue;
- (BOOL) stringValue;
- (KeyValuePairStringBoolBuilder*) setStringValue:(BOOL) value;
- (KeyValuePairStringBoolBuilder*) clearStringValue;
@end


// @@protoc_insertion_point(global_scope)
