// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class PositionModel;
@class PositionModelBuilder;



@interface PositionModelRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define PositionModel_PositionId @"positionId"
#define PositionModel_PositionName @"positionName"
#define PositionModel_FontColor @"fontColor"
@interface PositionModel : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPositionId_:1;
  BOOL hasPositionName_:1;
  BOOL hasFontColor_:1;
  SInt32 positionId;
  NSString* positionName;
  NSString* fontColor;
}
- (BOOL) hasPositionId;
- (BOOL) hasPositionName;
- (BOOL) hasFontColor;
@property (readonly) SInt32 positionId;
@property (readonly, strong) NSString* positionName;
@property (readonly, strong) NSString* fontColor;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PositionModelBuilder*) builder;
+ (PositionModelBuilder*) builder;
+ (PositionModelBuilder*) builderWithPrototype:(PositionModel*) prototype;
- (PositionModelBuilder*) toBuilder;

+ (PositionModel*) parseFromData:(NSData*) data;
+ (PositionModel*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PositionModel*) parseFromInputStream:(NSInputStream*) input;
+ (PositionModel*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PositionModel*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PositionModel*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PositionModelBuilder : PBGeneratedMessageBuilder {
@private
  PositionModel* resultPositionModel;
}

- (PositionModel*) defaultInstance;

- (PositionModelBuilder*) clear;
- (PositionModelBuilder*) clone;

- (PositionModel*) build;
- (PositionModel*) buildPartial;

- (PositionModelBuilder*) mergeFrom:(PositionModel*) other;
- (PositionModelBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PositionModelBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPositionId;
- (SInt32) positionId;
- (PositionModelBuilder*) setPositionId:(SInt32) value;
- (PositionModelBuilder*) clearPositionId;

- (BOOL) hasPositionName;
- (NSString*) positionName;
- (PositionModelBuilder*) setPositionName:(NSString*) value;
- (PositionModelBuilder*) clearPositionName;

- (BOOL) hasFontColor;
- (NSString*) fontColor;
- (PositionModelBuilder*) setFontColor:(NSString*) value;
- (PositionModelBuilder*) clearFontColor;
@end


// @@protoc_insertion_point(global_scope)
