// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class ProductStageModel;
@class ProductStageModelBuilder;



@interface ProductStageModelRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define ProductStageModel_ProductStageId @"productStageId"
#define ProductStageModel_ProductStageName @"productStageName"
#define ProductStageModel_FontColor @"fontColor"
@interface ProductStageModel : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasProductStageId_:1;
  BOOL hasProductStageName_:1;
  BOOL hasFontColor_:1;
  SInt32 productStageId;
  NSString* productStageName;
  NSString* fontColor;
}
- (BOOL) hasProductStageId;
- (BOOL) hasProductStageName;
- (BOOL) hasFontColor;
@property (readonly) SInt32 productStageId;
@property (readonly, strong) NSString* productStageName;
@property (readonly, strong) NSString* fontColor;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProductStageModelBuilder*) builder;
+ (ProductStageModelBuilder*) builder;
+ (ProductStageModelBuilder*) builderWithPrototype:(ProductStageModel*) prototype;
- (ProductStageModelBuilder*) toBuilder;

+ (ProductStageModel*) parseFromData:(NSData*) data;
+ (ProductStageModel*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProductStageModel*) parseFromInputStream:(NSInputStream*) input;
+ (ProductStageModel*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProductStageModel*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProductStageModel*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProductStageModelBuilder : PBGeneratedMessageBuilder {
@private
  ProductStageModel* resultProductStageModel;
}

- (ProductStageModel*) defaultInstance;

- (ProductStageModelBuilder*) clear;
- (ProductStageModelBuilder*) clone;

- (ProductStageModel*) build;
- (ProductStageModel*) buildPartial;

- (ProductStageModelBuilder*) mergeFrom:(ProductStageModel*) other;
- (ProductStageModelBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProductStageModelBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasProductStageId;
- (SInt32) productStageId;
- (ProductStageModelBuilder*) setProductStageId:(SInt32) value;
- (ProductStageModelBuilder*) clearProductStageId;

- (BOOL) hasProductStageName;
- (NSString*) productStageName;
- (ProductStageModelBuilder*) setProductStageName:(NSString*) value;
- (ProductStageModelBuilder*) clearProductStageName;

- (BOOL) hasFontColor;
- (NSString*) fontColor;
- (ProductStageModelBuilder*) setFontColor:(NSString*) value;
- (ProductStageModelBuilder*) clearFontColor;
@end


// @@protoc_insertion_point(global_scope)
