// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "CityModel.pb.h"
// @@protoc_insertion_point(imports)

@class AreaModel;
@class AreaModelBuilder;
@class CityModel;
@class CityModelBuilder;
@class ProvinceModel;
@class ProvinceModelBuilder;



@interface ProvinceModelRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define ProvinceModel_ProvinceId @"provinceId"
#define ProvinceModel_ProvinceName @"provinceName"
#define ProvinceModel_CityList @"cityList"
@interface ProvinceModel : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasProvinceId_:1;
  BOOL hasProvinceName_:1;
  SInt32 provinceId;
  NSString* provinceName;
  NSMutableArray * cityListArray;
}
- (BOOL) hasProvinceId;
- (BOOL) hasProvinceName;
@property (readonly) SInt32 provinceId;
@property (readonly, strong) NSString* provinceName;
@property (readonly, strong) NSArray * cityList;
- (CityModel*)cityListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProvinceModelBuilder*) builder;
+ (ProvinceModelBuilder*) builder;
+ (ProvinceModelBuilder*) builderWithPrototype:(ProvinceModel*) prototype;
- (ProvinceModelBuilder*) toBuilder;

+ (ProvinceModel*) parseFromData:(NSData*) data;
+ (ProvinceModel*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProvinceModel*) parseFromInputStream:(NSInputStream*) input;
+ (ProvinceModel*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProvinceModel*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProvinceModel*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProvinceModelBuilder : PBGeneratedMessageBuilder {
@private
  ProvinceModel* resultProvinceModel;
}

- (ProvinceModel*) defaultInstance;

- (ProvinceModelBuilder*) clear;
- (ProvinceModelBuilder*) clone;

- (ProvinceModel*) build;
- (ProvinceModel*) buildPartial;

- (ProvinceModelBuilder*) mergeFrom:(ProvinceModel*) other;
- (ProvinceModelBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProvinceModelBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasProvinceId;
- (SInt32) provinceId;
- (ProvinceModelBuilder*) setProvinceId:(SInt32) value;
- (ProvinceModelBuilder*) clearProvinceId;

- (BOOL) hasProvinceName;
- (NSString*) provinceName;
- (ProvinceModelBuilder*) setProvinceName:(NSString*) value;
- (ProvinceModelBuilder*) clearProvinceName;

- (NSMutableArray *)cityList;
- (CityModel*)cityListAtIndex:(NSUInteger)index;
- (ProvinceModelBuilder *)addCityList:(CityModel*)value;
- (ProvinceModelBuilder *)setCityListArray:(NSArray *)array;
- (ProvinceModelBuilder *)clearCityList;
@end


// @@protoc_insertion_point(global_scope)
